### ISSUE TITLE
Tests and solution are broken

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/cipher-challenge#25]
This used to be a browser-based challenge. For WDI 010, I converted it to node. That means instead of IIFEs, I chose to organize the code using an object literal.

I broke things, and I haven't fixed them yet.

**Comment by MicFin** [comment]
@jrhorn424 this can be closed.  It did not close when the `solution` branch was updated because we do not accept the PR for `solution`.

**Comment by jrhorn424** [comment]
Thanks @MicFin
